In [1]:
from pykalman import KalmanFilter
import torch
torch.set_default_dtype(torch.float64)
kf = KalmanFilter(transition_matrices = torch.tensor([[1, 1], [0, 1]],dtype=torch.float64), 
                  observation_matrices = torch.tensor([[0.1, 0.5], [-0.3, 0.0]],dtype=torch.float64))
measurements = torch.tensor([[1,0], [0,0], [0,1]],dtype=torch.float64)  # 3 observations
kf = kf.em(measurements, n_iter=5)
(filtered_state_means, filtered_state_covariances) = kf.filter(measurements)
(smoothed_state_means, smoothed_state_covariances) = kf.smooth(measurements)
print(filtered_state_means)

tensor([[-0.6324,  0.4873],
        [-0.0814,  0.3635],
        [-1.7297,  0.2964]])


D:\Documents\Grad2\Time Series\Project\TSA_GAN\src\pykalman\standard.py:1551: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(obs)
D:\Documents\Grad2\Time Series\Project\TSA_GAN\src\pykalman\standard.py:103: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X,dtype=torch.float64)
D:\Documents\Grad2\Time Series\Project\TSA_GAN\src\pykalman\standard.py:264: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  predicted_state_mean),dtype=torch.float64)
D:\Documents\Grad2\Time Series\Project\TSA_GAN\src\pykalman\standa

In [2]:
import torch
import numpy as np
x = torch.tensor([0.1000, 0.5000])
y = torch.tensor([[1., 0.],
           [0., 1.]])
print(np.dot(np.array([[1., 0.],[0., 1.]]),
          np.array([0.1000, 0.5000]).T))
print(x.reshape(1,list(x.size())[0]))
np.matmul(torch.tensor([[1., 0.],[0., 1.]]),x.reshape(list(x.size())[0],1))


[0.1 0.5]
tensor([[0.1000, 0.5000]])


tensor([[0.1000],
        [0.5000]])